
[package]
name    = "mold"
version = "0.1.0"
authors = ["Mehdi Vasigh <mehdi.vasigh@gmail.com>"]
edition = "2018"

[dependencies]
nannou  = "0.16"
lerp = "0.4.0"
rand_distr = "0.4.3"
rand = "0.8.4"
lazy_static = "1.4.0"